# Generated by Django 2.0.4 on 2018-05-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('tsc_no', models.IntegerField(verbose_name=50)),
            ],
            options={
                'verbose_name_plural': 'heads',
                'db_table': 'heads',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('reg_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('teacher_no', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'schools',
                'db_table': 'schools',
            },
        ),
        migrations.AddField(
            model_name='heads',
            name='school_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Schools'),
        ),
    ]
